#!/usr/bin/env bash
# Runs the Feature tests.
#
#   scripts/test-features.sh           # every scenario
#   scripts/test-features.sh ubuntu    # only scenarios whose name contains "ubuntu"
#
# The 1password-commit-signing scenarios mount a real SSH agent socket from
# the host in place of the 1Password one, so this script starts a throwaway
# agent holding a throwaway key before calling `devcontainer features test`,
# and stops it afterwards. Uses `devcontainer` from PATH, or npx if it isn't
# installed.
set -euo pipefail

cd "$(dirname "$0")/.."

agent_dir=/tmp/1password-commit-signing-test   # the path scenarios.json mounts

stop_agent() {
    if [ -n "${SSH_AGENT_PID:-}" ]; then
        kill "$SSH_AGENT_PID"
    fi
    rm -rf "$agent_dir"
}
trap stop_agent EXIT

rm -rf "$agent_dir"
mkdir -p "$agent_dir"
eval "$(ssh-agent -s -a "$agent_dir/agent.sock")" >/dev/null   # sets SSH_AGENT_PID
ssh-keygen -q -t ed25519 -N '' -f "$agent_dir/key"
SSH_AUTH_SOCK="$agent_dir/agent.sock" ssh-add -q "$agent_dir/key"

if command -v devcontainer >/dev/null; then
    devcontainer=devcontainer
else
    devcontainer="npx -y @devcontainers/cli"
fi

if [ $# -gt 0 ]; then
    $devcontainer features test --skip-autogenerated --filter "$1" .
else
    $devcontainer features test --skip-autogenerated .
fi
