#!/usr/bin/env bash
# Runs the Feature tests. Wraps `devcontainer features test` because the
# 1password-commit-signing scenarios need a real SSH agent socket on the
# host, mounted into the test container in place of the 1Password one.
#
#   scripts/test-features.sh              # every Feature, every scenario
#   scripts/test-features.sh ubuntu       # only scenarios whose name contains "ubuntu"
#
# Uses `devcontainer` from PATH, or npx if it isn't installed.
set -euo pipefail

cd "$(dirname "$0")/.."

agent_dir=/tmp/1password-commit-signing-test
agent_sock="$agent_dir/agent.sock"

cleanup() {
    if [ -n "${SSH_AGENT_PID:-}" ]; then
        kill "$SSH_AGENT_PID" 2>/dev/null || true
    fi
    rm -rf "$agent_dir"
}
trap cleanup EXIT

# A throwaway agent with a throwaway key, so the container can prove it can
# sign with an agent-held key through the forwarded socket.
rm -rf "$agent_dir"
mkdir -p "$agent_dir"
eval "$(ssh-agent -s -a "$agent_sock")" >/dev/null
ssh-keygen -q -t ed25519 -N '' -C "1password-commit-signing test" -f "$agent_dir/key"
SSH_AUTH_SOCK="$agent_sock" ssh-add -q "$agent_dir/key"

if command -v devcontainer >/dev/null 2>&1; then
    devcontainer=(devcontainer)
else
    devcontainer=(npx -y @devcontainers/cli)
fi

if [ $# -gt 0 ]; then
    "${devcontainer[@]}" features test --skip-autogenerated --filter "$1" .
else
    "${devcontainer[@]}" features test --skip-autogenerated .
fi
