#!/usr/bin/env bash
# Runs the Feature tests: scripts/test-features.sh [scenario-name-filter]
#
# Starts a throwaway ssh-agent holding a throwaway key, which the scenarios
# mount in place of the 1Password socket, then runs `devcontainer features
# test` (from PATH, or via npx) and stops the agent.
set -euo pipefail

cd "$(dirname "$0")/.."

agent_dir=/tmp/1password-commit-signing-test   # the path scenarios.json mounts

cleanup() {
    if [ -n "${SSH_AGENT_PID:-}" ]; then
        kill "$SSH_AGENT_PID"
    fi
    rm -rf "$agent_dir"
}
trap cleanup EXIT

rm -rf "$agent_dir"
mkdir -p "$agent_dir"
eval "$(ssh-agent -s -a "$agent_dir/agent.sock")" >/dev/null   # sets SSH_AGENT_PID
ssh-keygen -q -t ed25519 -N '' -f "$agent_dir/key"
SSH_AUTH_SOCK="$agent_dir/agent.sock" ssh-add -q "$agent_dir/key"

if command -v devcontainer >/dev/null; then
    devcontainer=devcontainer
else
    devcontainer="npx -y @devcontainers/cli"
fi

if [ $# -gt 0 ]; then
    set -- --filter "$1"
fi
$devcontainer features test --skip-autogenerated "$@" .
